### ISSUE TITLE
How do you import and install the libraries?

### ISSUE THREAD

**Issue by JoshuaBuker** [SwerveDriveSpecialties/swerve-template#2]
I am trying to setup a swerve drive using this template, however I cannot get the libraries installed so the code recognizes them. They show up in the vendordeps, but still show unresolved to type. Cannot seem to find any resources on how to do this that work, so any help is much appreciated. 

Thank you.

**Comment by jasondaming** [comment]
So you cloned this repository and it doesn't build?  What errors do you get? "but still show unresolved to type" is confusing can you post the exact error?  A picture would be nice!

**Comment by randomstring** [comment]
I found that if you clone the repository in VS Code you have to use "git: Clone (Recursive)" and not "git: Clone" so that it pulls in the recursive library repository. I'm not sure what the default is if you clone from the command line, but you might need to specify "--recursive"

**Comment by JoshuaBuker** [comment]
Sorry for not checking responses for a while. Ended up learning that our school's wifi blocked the jitpack file needed, so that is where all the issues came from. Got it unblocked and everything is working fine now. Nonetheless thank you for the responses.

**Comment by Not-AriStienfeld** [comment]
I'm new to coding in java and can't seem to be able to get the sds libraries to load. I git cloned recursively on home wifi with nothing blocked, yet com.swervedrivespecialties still isn't installing

**Comment by JoshuaBuker** [comment]
Not to sure on the rules here, so forgive me if links are not allowed. But when making this issue originally, I had gotten help on the Chief Delphi forum on how to setup the library. [Here is the link to the thread **](https://www.chiefdelphi.com/t/error-when-updating-to-2022-jdk-internal-loader-builtinclassloader/402278/14)** Following this thread may prove useful.
