### ISSUE TITLE
SparkMax Version

### ISSUE THREAD

**Issue by Quantum357** [SwerveDriveSpecialties/swerve-template#7]
I believe this is trying to access the wrong version of SparkMax firmware.  The latest firmware release from REV is v.1.5.2, while the REVRobotics.json is calling v.1.5.4.

This is giving my team errors when trying to use SparkMaxes on our robot.  Have any other teams experienced this?

**Comment by jasondaming** [comment]
This example has not been updated to 2022.  Teams should not be using REVRobotics.json they should be using REVLib.json.  For a version of this updated to 2022 see [this](https://github.com/jasondaming/2022-6391-Swerve).

**Comment by Quantum357** [comment]
I noticed you do not have SDS's swerve dependency in that repo.  Does it still work work?

**Comment by Quantum357** [comment]
Ah, thanks.  We updated our code with this and it solved the issue.
